package at.ac.uibk.dps.biohadoop.torename;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

public class ClassPathBuilder {
	
	public static List<URL> getLocalUrls() throws MalformedURLException {
		List<URL> libs = new ArrayList<URL>();
		libs.add(new File("/sdb/studium/master-thesis/code/git/masterthesis/target/biohadoop-0.0.1-SNAPSHOT.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/async-http-servlet-3.0/3.0.6.Final/async-http-servlet-3.0-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/javax/enterprise/cdi-api/1.1/cdi-api-1.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-codec/commons-codec/1.4/commons-codec-1.4.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/google/guava/guava/11.0.2/guava-11.0.2.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/hadoop/hadoop-auth/2.3.0/hadoop-auth-2.3.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/hadoop/hadoop-common/2.3.0/hadoop-common-2.3.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/hadoop/hadoop-hdfs/2.3.0/hadoop-hdfs-2.3.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/hadoop/hadoop-yarn-api/2.3.0/hadoop-yarn-api-2.3.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/hadoop/hadoop-yarn-client/2.3.0/hadoop-yarn-client-2.3.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/hadoop/hadoop-yarn-common/2.3.0/hadoop-yarn-common-2.3.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.2.1/jackson-annotations-2.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.2.1/jackson-core-2.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.2.1/jackson-databind-2.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-base/2.2.1/jackson-jaxrs-base-2.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/fasterxml/jackson/jaxrs/jackson-jaxrs-json-provider/2.2.1/jackson-jaxrs-json-provider-2.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.2.1/jackson-module-jaxb-annotations-2.2.1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/javassist/javassist/3.12.1.GA/javassist-3.12.1.GA.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/jaxrs-api/3.0.6.Final/jaxrs-api-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.1_spec/1.0.1.Final/jboss-annotations-api_1.1_spec-1.0.1.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Alpha1/jboss-annotations-api_1.2_spec-1.0.0.Alpha1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/classfilewriter/jboss-classfilewriter/1.0.4.Final/jboss-classfilewriter-1.0.4.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/spec/javax/el/jboss-el-api_3.0_spec/1.0.0.Alpha1/jboss-el-api_3.0_spec-1.0.0.Alpha1.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/spec/javax/interceptor/jboss-interceptors-api_1.2_spec/1.0.0.Alpha3/jboss-interceptors-api_1.2_spec-1.0.0.Alpha3.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/logging/jboss-logging/3.1.3.GA/jboss-logging-3.1.3.GA.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/spec/javax/servlet/jboss-servlet-api_3.1_spec/1.0.0.Final/jboss-servlet-api_3.1_spec-1.0.0.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/resteasy-cdi/3.0.6.Final/resteasy-cdi-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/resteasy-client/3.0.6.Final/resteasy-client-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/resteasy-jackson2-provider/3.0.6.Final/resteasy-jackson2-provider-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/resteasy-jaxrs/3.0.6.Final/resteasy-jaxrs-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/resteasy/resteasy-undertow/3.0.6.Final/resteasy-undertow-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/scannotation/scannotation/1.0.3/scannotation-1.0.3.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/slf4j/slf4j-log4j12/1.7.6/slf4j-log4j12-1.7.6.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/io/undertow/undertow-core/1.0.1.Final/undertow-core-1.0.1.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/io/undertow/undertow-servlet/1.0.1.Final/undertow-servlet-1.0.1.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/weld/weld-api/2.1.Final/weld-api-2.1.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/weld/weld-core-impl/2.1.2.Final/weld-core-impl-2.1.2.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/weld/se/weld-se-core/2.1.2.Final/weld-se-core-2.1.2.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/weld/weld-spi/2.1.Final/weld-spi-2.1.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/xnio/xnio-api/3.2.0.Final/xnio-api-3.2.0.Final.jar").toURI().toURL());
		libs.add(new File("/home/chris/.m2/repository/org/jboss/xnio/xnio-nio/3.2.0.Final/xnio-nio-3.2.0.Final.jar").toURI().toURL());
		return libs;
	}
	
	public static List<URL> getHadoopUrls() throws MalformedURLException {
		List<URL> libs = new ArrayList<URL>();
		libs.add(new File("biohadoop-0.0.1-SNAPSHOT.jar").toURI().toURL());
		libs.add(new File("activation-1.1.jar").toURI().toURL());
		libs.add(new File("async-http-servlet-3.0-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("cdi-api-1.1.jar").toURI().toURL());
		libs.add(new File("commons-cli-1.2.jar").toURI().toURL());
		libs.add(new File("commons-codec-1.4.jar").toURI().toURL());
		libs.add(new File("commons-collections-3.2.1.jar").toURI().toURL());
		libs.add(new File("commons-configuration-1.6.jar").toURI().toURL());
		libs.add(new File("commons-io-2.4.jar").toURI().toURL());
		libs.add(new File("commons-lang-2.6.jar").toURI().toURL());
		libs.add(new File("commons-logging-1.1.3.jar").toURI().toURL());
		libs.add(new File("guava-11.0.2.jar").toURI().toURL());
		libs.add(new File("hadoop-auth-2.3.0.jar").toURI().toURL());
		libs.add(new File("hadoop-common-2.3.0.jar").toURI().toURL());
		libs.add(new File("hadoop-hdfs-2.3.0.jar").toURI().toURL());
		libs.add(new File("hadoop-yarn-api-2.3.0.jar").toURI().toURL());
		libs.add(new File("hadoop-yarn-client-2.3.0.jar").toURI().toURL());
		libs.add(new File("hadoop-yarn-common-2.3.0.jar").toURI().toURL());
		libs.add(new File("httpclient-4.3.3.jar").toURI().toURL());
		libs.add(new File("httpcore-4.3.2.jar").toURI().toURL());
		libs.add(new File("jackson-annotations-2.2.1.jar").toURI().toURL());
		libs.add(new File("jackson-core-2.2.1.jar").toURI().toURL());
		libs.add(new File("jackson-databind-2.2.1.jar").toURI().toURL());
		libs.add(new File("jackson-jaxrs-base-2.2.1.jar").toURI().toURL());
		libs.add(new File("jackson-jaxrs-json-provider-2.2.1.jar").toURI().toURL());
		libs.add(new File("jackson-module-jaxb-annotations-2.2.1.jar").toURI().toURL());
		libs.add(new File("javassist-3.12.1.GA.jar").toURI().toURL());
		libs.add(new File("javax.inject-1.jar").toURI().toURL());
		libs.add(new File("jaxrs-api-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("jboss-annotations-api_1.1_spec-1.0.1.Final.jar").toURI().toURL());
		libs.add(new File("jboss-annotations-api_1.2_spec-1.0.0.Alpha1.jar").toURI().toURL());
		libs.add(new File("jboss-classfilewriter-1.0.4.Final.jar").toURI().toURL());
		libs.add(new File("jboss-el-api_3.0_spec-1.0.0.Alpha1.jar").toURI().toURL());
		libs.add(new File("jboss-interceptors-api_1.2_spec-1.0.0.Alpha3.jar").toURI().toURL());
		libs.add(new File("jboss-logging-3.1.3.GA.jar").toURI().toURL());
		libs.add(new File("jboss-servlet-api_3.1_spec-1.0.0.Final.jar").toURI().toURL());
		libs.add(new File("jcip-annotations-1.0.jar").toURI().toURL());
		libs.add(new File("log4j-1.2.17.jar").toURI().toURL());
		libs.add(new File("protobuf-java-2.5.0.jar").toURI().toURL());
		libs.add(new File("resteasy-cdi-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("resteasy-client-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("resteasy-jackson2-provider-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("resteasy-jaxrs-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("resteasy-undertow-3.0.6.Final.jar").toURI().toURL());
		libs.add(new File("scannotation-1.0.3.jar").toURI().toURL());
		libs.add(new File("slf4j-api-1.7.5.jar").toURI().toURL());
		libs.add(new File("slf4j-log4j12-1.7.6.jar").toURI().toURL());
		libs.add(new File("undertow-core-1.0.1.Final.jar").toURI().toURL());
		libs.add(new File("undertow-servlet-1.0.1.Final.jar").toURI().toURL());
		libs.add(new File("weld-api-2.1.Final.jar").toURI().toURL());
		libs.add(new File("weld-core-impl-2.1.2.Final.jar").toURI().toURL());
		libs.add(new File("weld-se-core-2.1.2.Final.jar").toURI().toURL());
		libs.add(new File("weld-spi-2.1.Final.jar").toURI().toURL());
		libs.add(new File("xnio-api-3.2.0.Final.jar").toURI().toURL());
		libs.add(new File("xnio-nio-3.2.0.Final.jar").toURI().toURL());
        return libs;
	}
	
}
